### ISSUE TITLE
Make project less windows specific

### ISSUE THREAD

**Issue by KSPAtlas** [Chadx86/chadx86#1]
pls i use linux

**Comment by PedroElFrijol** [comment]
I am pretty sure you can use this on Linux too

**Comment by 0xol** [comment]
The current build system only works with a bash/zsh terminal

**Comment by KSPAtlas** [comment]
> The current build system only works with a bash/zsh terminal

What is the build.bat there for then?

**Comment by KSPAtlas** [comment]
Also it uses mingw

**Comment by 0xol** [comment]
Build.bat is a retired build script 
also less windows specific? are you suggesting windows users shouldnt be able to use and compile the bootloader
and MinGW is for linux and windows

**Comment by InsaneMiner** [comment]
> Also it uses mingw

have you tried compiling the bootloader?
